#  server-port配置
server:
  port: 8080

#  spring配置
spring:
    http:
        # (这里是限制的文件大小)
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 20MB
    datasource:
        name: test
        #  数据库连接地址
        url: jdbc:mysql://127.0.0.1:3306/zls?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: 11111111
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource   #  配置当前要使用的数据源的操作类型
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
## 下面mybatis该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #  配置文件所在路径
  mapper-locations: classpath:mybatis/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cp.cpspringboot  # 注意：对应实体类的路径.model  
          
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
#<!-- 设置为true时，会将RowBounds第一个參数offset当成pageNum页码使用 -->
#<!-- 和startPage中的pageNum效果一样-->
    offsetAsPageNum: true
#<!-- 该參数默觉得false -->
#<!-- 设置为true时，使用RowBounds分页会进行count查询 -->
    rowBoundsWithCount: true
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
    
    